name: blue_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_blue_classic: ^0.0.4
  flutter_joystick: ^0.2.1
  intl: ^0.20.2
  permission_handler: ^11.4.0
  provider: ^6.1.4
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
