name: blue_connect
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.7.2

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_blue_classic: ^0.0.4
  flutter_joystick: ^0.2.1
  flutter_svg: ^2.0.9  # Added for SVG support
  intl: ^0.20.2
  permission_handler: ^11.4.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/png/
